# Starship prompt config - themed by omarchy
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#bac2de)\
[ ⮝ ](bg:#bac2de fg:#1e1e2e)\
[](bg:#89b4fa fg:#bac2de)\
$directory\
[](fg:#89b4fa bg:#45475a)\
$git_branch\
$git_status\
[](fg:#45475a bg:#585b70)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#585b70)\
$character"""

[directory]
style = "fg:#cdd6f4 bg:#89b4fa"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#45475a"
format = '[[ $symbol $branch ](fg:#89b4fa bg:#45475a)]($style)'

[git_status]
style = "bg:#45475a"
format = '[[($all_status$ahead_behind )](fg:#89b4fa bg:#45475a)]($style)'

[nodejs]
symbol = ""
style = "bg:#585b70"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#585b70)]($style)'

[rust]
symbol = ""
style = "bg:#585b70"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#585b70)]($style)'

[golang]
symbol = ""
style = "bg:#585b70"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#585b70)]($style)'

[php]
symbol = ""
style = "bg:#585b70"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#585b70)]($style)'
